# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsk < Formula
  desc "ecsk is a CLI tool to interactively use frequently used functions of docker command in Amazon ECS. (docker run, exec, cp, logs, stop)"
  homepage "https://github.com/yukiarrr/ecsk"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yukiarrr/ecsk/releases/download/v0.9.1/ecsk_Darwin_arm64.tar.gz"
      sha256 "1aeced5c35ea181de5d249bf29a3861cc2f359de8cd820f7533513770b0c6538"

      def install
        bin.install "ecsk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yukiarrr/ecsk/releases/download/v0.9.1/ecsk_Darwin_x86_64.tar.gz"
      sha256 "352cd9b2605ab7f9d62a2cccefe6452daffa3a0f15c2af1196b70423ca584583"

      def install
        bin.install "ecsk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yukiarrr/ecsk/releases/download/v0.9.1/ecsk_Linux_x86_64.tar.gz"
      sha256 "28905a89c9cd897c05f44f8d4a2b70548b13a7a305eb004c12e2dc71692a4444"

      def install
        bin.install "ecsk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yukiarrr/ecsk/releases/download/v0.9.1/ecsk_Linux_arm64.tar.gz"
      sha256 "2b002af9b941a4b21197c8a0ade964dde93ed4ef5afb3abc81fb3f655054c60b"

      def install
        bin.install "ecsk"
      end
    end
  end

  test do
    system "#{bin}/ecsk -v"
  end
end
